# -------------------------------
#     HLR v1.0.0 config file
#    Created by despawningbone
# ------------------------------- 

# Choose which worlds the tweaked hopper will work in.
Enabled-in-worlds: 
  - world
  
# Here you can choose what type of items the tweaked hopper will take in.
ItemList:
  # This includes all the common crops, i.e. Pumpkin, Cactus, Wheat, Seeds, Carrot,
  # Potato(including Poisonous ones), Sugarcane, Red/Brown Mushrooms, Melons and Nether warts.  
  Crops: true
  # This includes all the common mob drops, i.e. Feather, Raw chicken, Raw Beef, Raw Porkchop,
  # Raw mutton, Spider eye, Ender pearl, Bone, Arrow, Wool, Iron Ingot, Blaze rod, Gunpowder,
  # String, Gold nugget, Slimeball, Ink sack, Leather, Rotten Flesh, Prismarine Shard, Prismarine Crystals and Raw Fish.
  Mob-drops: true
  # Here you can add the custom items you want to be taken in by the tweaked hopper.
  # Please use Bukkit's material list's name.
  Custom-items:
  # - EXAMPLE_MATERIAL
    -

# Here you can set how many hoppers can be converted at once.
# e.g. Max-amount: 5, players can't convert a stack of hoppers with more than 5 hoppers in it.
Max-amount: 10

# Use permissions? Vault API required
Use-permissions: true

# Enable /converthopper cooldown?
Cooldown:
  Enable: false
  Seconds: 30
  
# You can rename the tweaked hopper here.
Hopper-name: "&3Farming &fHopper"

# You can set the lore of the tweaked hopper here.
Hopper-lore: 
  - "&7This hopper is special."
  - "&7It can find specific items"
  - "&7And teleport the items to it instantly."

# Use economy? Vault API required
Eco:
  Use: false
  Conversion-fee: 0.0

