name: HLR
description: A plugin which adds a special type of Hoppers which collects configurable drops instantly, reducing lag and avoiding drop loss.
version: 1.0.2
author: despawningbone

main: me.despawningbone.HLR.HLRmain
softdepend: [Vault]

commands:
    converthopper:
        description: converts normal hopper to a specific one.
        usage: /<command> [type]
        aliases: [chopper]
    hlr:
        description: sub-commands of this plugin.
        usage: /<command> [help/about/reload]
